apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: microservices
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
