apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - namespace.yaml
  - configmap.yaml

# Add service directories here
# - ../services/user-service
# - ../services/order-service
# - ../services/gateway-service
